name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish
    - name: copy license
      run: cp LICENSE.txt ./LocalNetworkCrawler/publish/
    - name: copy readme
      run: cp README.md ./LocalNetworkCrawler/publish/
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: build.zip
        directory: ./LocalNetworkCrawler/publish/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: build
        path: build.zip
